app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|post,get,put,delete
*/
//EJEMPLOS DE RUTAS:
// Route::get('prueba', function (){
//   return "Hola desde routes.php";
// });
// Route::get('nombre/{nombre}',function($nombre){
//   return "Mi nombre es: ".$nombre;
// });
// Route::get('edad/{edad?}',function($edad = 26){
//   return "Mi edad es: ".$edad;
// });
// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('controlador','PruebaController@index');//@index hace referencia al metodo index del controlador
// Route::get('name/{nombre}','PruebaController@nombre');
// Route::resource('movie','MovieController');
Route::get('/','FrontController@index');
Route::get('contact','FrontController@contact');
Route::get('reviews','FrontController@reviews');
Route::get('admin','FrontController@admin');

Route::resource('usuario','UsuarioController');
Route::get('usuario/{usuario}/destroy',[
  'uses'=>'UsuarioController@destroy',
  'as' => 'usuario.destroy'
]);
Route::resource('genero','GeneroController');
Route::resource('pelicula','MovieController');
Route::get('pelicula/{pelicula}/destroy',[
  'uses'=>'MovieController@destroy',
  'as' => 'pelicula.destroy'
]);
//Route::resource('login','LogController');
Route::post('login',['uses'=>'LoginController@login','as'=>'login.login']);
Route::get('logout',['uses'=>'LoginController@logout','as'=>'login.logout']);//*

resources/views/pelicula/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.required')
		  	{!!Form::open(['route'=>'pelicula.store', 'method'=>'POST','files' => true])!!}
				<div class="users">
				<section class="content">
				  <div class="row">
				    <div class="col-xs-12">
				      <div class="box">
				        <div class="box-header">
				          <h3 class="box-title">Pelicula</h3>
				        </div>
				        <!-- /.box-header -->
				        <div class="box-body">
		  		@include('pelicula.forms.pelicula')
				{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
			</div>
			</div>
		</div>
		</div>
			</section>
			</div>
			{!!Form::close()!!}
	@endsection

resources/views/pelicula/edit.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.required')
		
		<div class="users">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Pelicula</h3>
						</div>
						<!-- /.box-header -->
						<div class="box-body">
		{!!Form::model($movie,['route'=> ['pelicula.update',$movie->id],'method'=>'PUT','files' => true])!!}
			@include('pelicula.forms.pelicula')
			{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
		{!!Form::close()!!}

		{!!Form::open(['route'=> ['pelicula.destroy',$movie->id],'method'=>'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
		{!!Form::close()!!}
	</div>
	</div>
</div>
</div>
	</section>
	</div>
	@endsection

resources/views/pelicula/index.blade.php
@extends('layouts.admin')
	@include('alerts.success')
	@section('content')
		<div class="users">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Peliculas</h3>
						</div>
						<!-- /.box-header -->
						<div class="box-body">
		<table class="table">
			<thead>
				<th>Nombre</th>
				<th>Genero</th>
				<th>Direccion</th>
				<th>Caratula</th>
				<th>Operaciones</th>
			</thead>
			@foreach($movies as $movie)
				<tbody>
					<td>{{$movie->name}}</td>
					<td>{{$movie->genre}}</td>
					<td>{{$movie->direction}}</td>
					<td>
						<img src="movies/{{$movie->path}}" alt="" style="width:100px;"/>
					</td>
					<td>{!!link_to_route('pelicula.edit', $title = 'Editar', $parameters = $movie->id, $attributes = ['class'=>'btn btn-primary'])!!}
					{!!link_to_route('pelicula.destroy',$title = 'Eliminar',$parameteres = $movie->id,$attributes = ['class'=>'btn btn-danger','onclick'=>'return confirm("¿Estas seguro de querer eliminar?")'])!!}</td></td>
				</tbody>
			@endforeach
		</table>
	</div>
	</div>
</div>
</div>
	</section>
	</div>
	@endsection